### ISSUE TITLE
Add end to end test cases

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#118]
This is the top level issue about implementing e2e test for the driver. The tests will exercise the driver functionalities along with kubernetes being the CO. The functionalities includes:

*Happy Scenarios*:
 - [x] It("should create a PV object, bind to a PVC and be deleted with Delete reclaimPolicy")
 - [x] It("should create a PV object, bind to a PVC and be retained with Retain reclaimPolicy")
 - [x] It("should create multiple PV objects, bind to PVCs and attach each to different pods on the same node") (#151)
 - [x] It("should allow for provisioning with different volume types (gp2, io1, sc1, st1)") (#151)
 - [x] It("should allow for provisioning with different file system types (ext2, ext3, ext4, etc)") (#151)
 - [x] It("should allow for provisioning with specified zone in allowedTopologies")
 - [x] It("should allow for volume provisioning with encryption enabled")
 - [x] It("should allow for topology aware volume provisioning")
 - [x] It("should allow for statically creating a PV and writing and reading data")
 - [x] It("should allow for mounting volume with mount options")
 - [ ] ~It("should allow for a pod writing and reading data, expanding the PersistentVolume and writing and reading data") (depends volume resizing)~ (will do this when feature is being implemented)

*Failure Scenarios*:
 - [x] It("should reattach a volume after a pod is deleted and data can be read")
 - [ ] ~It("should reattach a volume after a pod is rescheduled from a drained node and data can be read")~ (punt to #189)

The test will be a go test using ginkgo as behavioral driven testing. It should assume that a cluster is already pre-created and the EBS CSI driver is already deployed for the test to run. 

**In Scope**
For each test case, the test should create a storageclass, create a pvc/pvc and verifies that certain conditions is met given the test scenario.

**Out of scope**
The following will be tracked separately and implemented as part of the [general testing framework](https://github.com/aws/aws-k8s-tester) for testing k8s on AWS:

* Building test driver container image
* Pushing test driver image to registry
* Setting up cluster
* Deploying test driver

**Comment by gyuho** [comment]
Ack. We should have this ready by next quarter.

**Comment by bertinatto** [comment]
:+1: 

@gyuho, @leakingtapan: just to make sure, perhaps are you working on this already?

**Comment by leakingtapan** [comment]
I have some ideas and will implement one test case and send PR to see how it looks like. After that we can break this down into sub tasks one per test case. 

/assign

**Comment by leakingtapan** [comment]
To clarify a bit, the scope of this issue is to write e2e test cases so that we can at least run test against our personal cluster endpoint quickly. This will be an big improvement over manual testing. 

And the work to set k8s cluster and the EBS CSI driver will be tracked separately by @gyuho and after that is done we will get full e2e test automation and integration with Prow.

**Comment by leakingtapan** [comment]
I updated the issue description and break down the test cases
